import 'dotenv/config';
import express from 'express';
import crypto from 'crypto';
import axios from 'axios';
import {
  Client,
  GatewayIntentBits,
  Partials,
  ButtonBuilder,
  ButtonStyle,
  ActivityType,
  ActionRowBuilder,
  PermissionsBitField,
} from 'discord.js';
import { v2 as cloudinary } from 'cloudinary';
import { createClient } from '@supabase/supabase-js';

const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_KEY);
const ytRegex = /(?:youtube\.com\/watch\?v=|youtu\.be\/)([a-zA-Z0-9_-]{11})/;
const nicoRegex = /(?:nicovideo\.(?:jp|gay)\/watch\/)(sm\d+|nm\d+)/;

cloudinary.config({
  cloud_name: process.env.CLOUDY_NAME,
  api_key: process.env.CLOUDY_API_KEY,
  api_secret: process.env.CLOUDY_API_SECRET,
});

const client = new Client({
  intents: [
    GatewayIntentBits.Guilds,
    GatewayIntentBits.GuildMessages,
    GatewayIntentBits.MessageContent,
    GatewayIntentBits.DirectMessages,
    GatewayIntentBits.GuildMembers,
    GatewayIntentBits.GuildMessageReactions, // ★リアクション検知に必要
  ],
  partials: [
    Partials.Channel,  // DM対応
    Partials.Message,  // 古いメッセージへのリアクション対応
    Partials.Reaction, // リアクションのpartial対応
    Partials.User,      // ユーザーのpartial対応
  ],
});

const PORT = process.env.PORT || 10000;
let botLoggedIn = false; // BOTログイン状態

async function loginBot() {
  if (botLoggedIn) return;
  try {
    await client.login(process.env.BOT_TOKEN);
    botLoggedIn = true;
    console.log(`✅ BOT logged in as ${client.user.tag}`);
  } catch (err) {
    console.error('❌ BOTログイン失敗:', err);
    botLoggedIn = false;
  }
}
loginBot();

const app = express();
app.get('/', async (req, res) => {
  if (!botLoggedIn) {
    return res.send('BOTは現在オフラインです。再起動してください。');
  }
  res.send(`BOTはオンラインです: ${client.user.tag}`);
});
app.listen(PORT, '0.0.0.0', () => {
  console.log(`🌐 HTTPサーバー起動: http://0.0.0.0:${PORT}`);
});

client.once('ready', () => {
  console.log(`${client.user.tag}にログインしたよ!`);
  client.user.setActivity('ﾊﾟﾐｭ～☆', { type: ActivityType.Watching });
  client.user.setStatus('online');
});

/* ============================================================
 * エラーログ送信
 *
 * .env に LOG_CHANNEL_ID（ログを送りたいチャンネルのID）を設定してください。
 * 未設定の場合はコンソール出力のみになります。
 * ============================================================ */

async function sendErrorLog(title, error, context = {}) {
  const detail = error instanceof Error ? (error.stack || error.message) : String(error);
  console.error(`❌ ${title}:`, detail);

  if (!process.env.LOG_CHANNEL_ID) return;
  if (!botLoggedIn) return; // ログイン前は送信できない

  try {
    const logChannel = await client.channels.fetch(process.env.LOG_CHANNEL_ID);
    if (!logChannel || !logChannel.isTextBased()) return;

    const contextLines = Object.entries(context)
      .map(([key, value]) => `${key}: ${value}`)
      .join('\n');

    // Discordのメッセージ上限(2000文字)を考慮して切り詰め
    const detailTrimmed = detail.length > 1500 ? detail.slice(0, 1500) + '...(省略)' : detail;

    await logChannel.send({
      content:
        `⚠️ **エラー発生: ${title}**\n` +
        (contextLines ? `${contextLines}\n` : '') +
        `\`\`\`${detailTrimmed}\`\`\``,
    });
  } catch (logSendError) {
    // ログ送信自体の失敗はコンソールにのみ出す（無限ループ防止のためsendErrorLogは呼ばない）
    console.error('❌ ログチャンネルへの送信に失敗:', logSendError.message);
  }
}

/* ============================================================
 * ユーティリティ
 * ============================================================ */

function isAdmin(member) {
  if (!member) return false;
  return member.permissions.has(PermissionsBitField.Flags.Administrator);
}

function extractRoleId(text) {
  const mentionMatch = text.match(/<@&(\d+)>/);
  if (mentionMatch) return mentionMatch[1];
  const idMatch = text.match(/^\d{15,20}$/);
  if (idMatch) return idMatch[0];
  return null;
}

// カスタム絵文字 <:name:id> / <a:name:id> / Unicode絵文字 から
// DB保存用のキーを作る。カスタム絵文字はID、それ以外はそのままの文字を使う。
function extractEmojiKey(text) {
  const customMatch = text.match(/<a?:\w+:(\d+)>/);
  if (customMatch) return customMatch[1];
  const trimmed = text.trim();
  return trimmed.length > 0 ? trimmed : null;
}

// discord.js の ReactionEmoji / GuildEmoji オブジェクトからキーを作る（イベント側で使用）
function emojiKeyFromReactionEmoji(emoji) {
  return emoji.id ? emoji.id : emoji.name;
}

/* ============================================================
 * Supabase: reaction_roles / mention_roles テーブルを利用
 *
 * 事前に以下のテーブルをSupabase上に作成してください:
 *
 * create table reaction_roles (
 *   id bigint generated by default as identity primary key,
 *   guild_id text not null,
 *   message_id text not null,
 *   emoji_key text not null,
 *   role_id text not null,
 *   created_at timestamptz default now(),
 *   unique (message_id, emoji_key)
 * );
 *
 * create table mention_roles (
 *   guild_id text primary key,
 *   role_id text not null
 * );
 * ============================================================ */

async function addReactionRoleMapping(guildId, messageId, emojiKey, roleId) {
  const { error } = await supabase
    .from('reaction_roles')
    .upsert(
      [{ guild_id: guildId, message_id: messageId, emoji_key: emojiKey, role_id: roleId }],
      { onConflict: 'message_id,emoji_key' }
    );
  return { ok: !error, error };
}

async function removeReactionRoleMapping(messageId, emojiKey) {
  const { error } = await supabase
    .from('reaction_roles')
    .delete()
    .eq('message_id', messageId)
    .eq('emoji_key', emojiKey);
  return { ok: !error, error };
}

async function getReactionRoleMapping(messageId, emojiKey) {
  const { data, error } = await supabase
    .from('reaction_roles')
    .select('role_id')
    .eq('message_id', messageId)
    .eq('emoji_key', emojiKey)
    .maybeSingle();
  if (error || !data) return null;
  return data.role_id;
}

async function listReactionRoleMappings(guildId) {
  const { data, error } = await supabase
    .from('reaction_roles')
    .select('message_id, emoji_key, role_id')
    .eq('guild_id', guildId);
  if (error) return [];
  return data;
}

async function setMentionRole(guildId, roleId) {
  const { error } = await supabase
    .from('mention_roles')
    .upsert([{ guild_id: guildId, role_id: roleId }], { onConflict: 'guild_id' });
  return { ok: !error, error };
}

async function getMentionRole(guildId) {
  const { data, error } = await supabase
    .from('mention_roles')
    .select('role_id')
    .eq('guild_id', guildId)
    .maybeSingle();
  if (error || !data) return null;
  return data.role_id;
}

/* ============================================================
 * メッセージ処理
 * ============================================================ */

client.on('messageCreate', async (message) => {
  if (message.author.bot) return;
  if (!message.guild) return; // コマンド類はサーバー内のみ対象

  const content = message.content.trim();

  /* ---- 管理者向けコマンド ---- */

  // !setmentionrole @ロール または ロールID
  if (content.startsWith('!setmentionrole')) {
    if (!isAdmin(message.member)) {
      return message.reply('この操作には管理者権限が必要だよ。');
    }
    const roleId = extractRoleId(content.replace('!setmentionrole', '').trim());
    if (!roleId) {
      return message.reply('使い方: `!setmentionrole @ロール名`');
    }
    const role = await message.guild.roles.fetch(roleId).catch(() => null);
    if (!role) return message.reply('そのロールが見つからなかったよ。');

    const { ok, error } = await setMentionRole(message.guild.id, roleId);
    if (!ok) {
      await sendErrorLog('メンションロール設定の保存失敗', error, {
        guild: message.guild.name,
        roleId,
      });
    }
    return message.reply(
      ok
        ? `BOTがメンションされたら「${role.name}」を自動付与するように設定したよ！`
        : '設定の保存に失敗しちゃった…もう一回試してみて。'
    );
  }

  // !addreactrole <messageId> <絵文字> @ロール
  if (content.startsWith('!addreactrole')) {
    if (!isAdmin(message.member)) {
      return message.reply('この操作には管理者権限が必要だよ。');
    }
    const parts = content.split(/\s+/);
    if (parts.length < 4) {
      return message.reply('使い方: `!addreactrole <メッセージID> <絵文字> @ロール`');
    }
    const targetMessageId = parts[1];
    const emojiKey = extractEmojiKey(parts[2]);
    const roleId = extractRoleId(parts.slice(3).join(' '));

    if (!emojiKey) return message.reply('絵文字が正しく認識できなかったよ。');
    if (!roleId) return message.reply('ロールが正しく指定されていないよ。');

    const targetMessage = await message.channel.messages.fetch(targetMessageId).catch(() => null);
    if (!targetMessage) {
      return message.reply('指定されたメッセージIDがこのチャンネル内で見つからなかったよ。');
    }

    // BOT自身が先にリアクションしておく（ユーザーが押しやすいように）
    try {
      const customEmojiMatch = parts[2].match(/<a?:(\w+):(\d+)>/);
      if (customEmojiMatch) {
        await targetMessage.react(customEmojiMatch[2]);
      } else {
        await targetMessage.react(parts[2]);
      }
    } catch (e) {
      await sendErrorLog('初期リアクション付与に失敗', e, {
        messageId: targetMessageId,
        emoji: parts[2],
      });
    }

    const { ok, error } = await addReactionRoleMapping(message.guild.id, targetMessageId, emojiKey, roleId);
    if (!ok) {
      await sendErrorLog('リアクションロール登録失敗', error, {
        guild: message.guild.name,
        messageId: targetMessageId,
        emojiKey,
        roleId,
      });
    }
    return message.reply(
      ok
        ? 'リアクションロールを登録したよ！このリアクションを付けると対象ロールが付与されるよ。'
        : '登録に失敗しちゃった…もう一回試してみて。'
    );
  }

  // !removereactrole <messageId> <絵文字>
  if (content.startsWith('!removereactrole')) {
    if (!isAdmin(message.member)) {
      return message.reply('この操作には管理者権限が必要だよ。');
    }
    const parts = content.split(/\s+/);
    if (parts.length < 3) {
      return message.reply('使い方: `!removereactrole <メッセージID> <絵文字>`');
    }
    const targetMessageId = parts[1];
    const emojiKey = extractEmojiKey(parts[2]);
    if (!emojiKey) return message.reply('絵文字が正しく認識できなかったよ。');

    const { ok, error } = await removeReactionRoleMapping(targetMessageId, emojiKey);
    if (!ok) {
      await sendErrorLog('リアクションロール解除失敗', error, {
        guild: message.guild.name,
        messageId: targetMessageId,
        emojiKey,
      });
    }
    return message.reply(ok ? 'リアクションロールの登録を解除したよ。' : '解除に失敗しちゃった。');
  }

  // !listreactroles
  if (content.startsWith('!listreactroles')) {
    if (!isAdmin(message.member)) {
      return message.reply('この操作には管理者権限が必要だよ。');
    }
    const list = await listReactionRoleMappings(message.guild.id);
    if (list.length === 0) return message.reply('登録されているリアクションロールはまだないよ。');
    const lines = list.map(
      (r) => `メッセージID: ${r.message_id} / 絵文字キー: ${r.emoji_key} / ロール: <@&${r.role_id}>`
    );
    return message.reply(lines.join('\n'));
  }

  /* ---- メンションによる自動ロール付与 ----
   * BOTがメンションされたら、発言者に設定済みロールを自動付与します。 */
  if (message.mentions.has(client.user)) {
    const roleId = await getMentionRole(message.guild.id);
    if (roleId) {
      const role = await message.guild.roles.fetch(roleId).catch(() => null);
      if (role) {
        try {
          await message.member.roles.add(role);
          await message.reply(`「${role.name}」ロールを付与したよ！`);
        } catch (e) {
          await sendErrorLog('メンションロール付与失敗', e, {
            user: `${message.author.tag} (${message.author.id})`,
            role: role.id,
            guild: message.guild.name,
          });
          await message.reply('ロールの付与に失敗しちゃった…BOTの権限を確認してね。');
        }
      }
    }
  }

  /* ---- 既存の動画掲載許可フロー ---- */
  if (message.channel.id !== '1487031369430204417') return;

  const row = new ActionRowBuilder().addComponents(
    new ButtonBuilder().setCustomId('approve_post').setLabel('掲載を許可する').setStyle(ButtonStyle.Success),
    new ButtonBuilder().setCustomId('deny_post').setLabel('許可しない').setStyle(ButtonStyle.Danger)
  );

  const matchYT = message.content.match(ytRegex);
  if (matchYT) {
    const videoId = matchYT[1];
    await message.reply({
      content:
        `この作品をサーバー公式サイトに掲載しちゃう？${videoId} \n` +
        `* ※許可を頂いた場合、当サイトの[利用規約・免責事項](https://blog2.chauchaucat.f5.si/)に同意したものとみなします。\n` +
        `* ※掲載後、削除を希望される場合は @ChauChauCat へ別途お問い合わせください。`,
      components: [row],
    });
  }

  const matchNC = message.content.match(nicoRegex);
  if (matchNC) {
    const videoId = matchNC[1];
    await message.reply({
      content:
        `この作品をサーバー公式サイトに掲載しちゃう？${videoId} \n` +
        `* ※許可を頂いた場合、当サイトの[利用規約・免責事項](https://blog2.chauchaucat.f5.si/)に同意したものとみなします。\n` +
        `* ※掲載後、削除を希望される場合は @ChauChauCat へ別途お問い合わせください。`,
      components: [row],
    });
  }
});

/* ============================================================
 * リアクションロール処理（付与・剥奪）
 * ============================================================ */

async function resolvePartials(reaction, user) {
  try {
    if (reaction.partial) await reaction.fetch();
  } catch (e) {
    await sendErrorLog('リアクションのfetch失敗', e);
    return false;
  }
  try {
    if (user.partial) await user.fetch();
  } catch (e) {
    await sendErrorLog('ユーザーのfetch失敗', e);
    return false;
  }
  return true;
}

client.on('messageReactionAdd', async (reaction, user) => {
  if (user.bot) return;
  const ok = await resolvePartials(reaction, user);
  if (!ok) return;

  const message = reaction.message;
  if (!message.guild) return;

  const emojiKey = emojiKeyFromReactionEmoji(reaction.emoji);
  const roleId = await getReactionRoleMapping(message.id, emojiKey);
  if (!roleId) return; // 登録されていないリアクションは無視

  const member = await message.guild.members.fetch(user.id).catch(() => null);
  const role = member ? await message.guild.roles.fetch(roleId).catch(() => null) : null;
  if (!member || !role) return;

  try {
    await member.roles.add(role);
    console.log(`✅ ${user.tag} に ${role.name} を付与`);
  } catch (e) {
    await sendErrorLog('リアクションロール付与失敗', e, {
      user: `${user.tag} (${user.id})`,
      role: role.id,
      messageId: message.id,
    });
  }
});

client.on('messageReactionRemove', async (reaction, user) => {
  if (user.bot) return;
  const ok = await resolvePartials(reaction, user);
  if (!ok) return;

  const message = reaction.message;
  if (!message.guild) return;

  const emojiKey = emojiKeyFromReactionEmoji(reaction.emoji);
  const roleId = await getReactionRoleMapping(message.id, emojiKey);
  if (!roleId) return;

  const member = await message.guild.members.fetch(user.id).catch(() => null);
  const role = member ? await message.guild.roles.fetch(roleId).catch(() => null) : null;
  if (!member || !role) return;

  try {
    await member.roles.remove(role);
    console.log(`🔻 ${user.tag} から ${role.name} を剥奪`);
  } catch (e) {
    await sendErrorLog('リアクションロール剥奪失敗', e, {
      user: `${user.tag} (${user.id})`,
      role: role.id,
      messageId: message.id,
    });
  }
});

/* ============================================================
 * ボタン（動画掲載許可フロー）
 * ============================================================ */

client.on('interactionCreate', async (interaction) => {
  if (!interaction.isButton()) return;
  if (interaction.customId === 'approve_post' || interaction.customId === 'deny_post') {
    const messageReference = interaction.message.reference;

    if (!messageReference || !messageReference.messageId) {
      return await interaction.message.delete().catch(() => {});
    }

    try {
      const originalMessage = await interaction.channel.messages.fetch(messageReference.messageId);

      if (interaction.user.id !== originalMessage.author.id) {
        return await interaction.reply({
          content: 'ごめん君にこの操作をする権限はないんだ',
          ephemeral: true,
        });
      }
      const content = originalMessage.content;
      console.log(`本人確認完了 (ID: ${originalMessage.author.id}) - アクション: ${interaction.customId}`);

      const statusText = interaction.customId === 'approve_post' ? 'して' : 'しないで';
      await interaction.reply({
        content:
          `じゃあ掲載${statusText}おくね！` +
          `${interaction.customId === 'approve_post' ? '\n * ※掲載の取り消しを希望する場合は @ChauChauCat へお問い合わせください' : ''}`,
        ephemeral: true,
      });
      await interaction.message.delete().catch(() => {});
      if (interaction.customId === 'approve_post') {
        const id = await getAndSaveVideoInfo(content);
        if (!id) {
          await sendErrorLog('動画情報の取得に失敗（掲載できず）', new Error('getAndSaveVideoInfoがnullを返した'), {
            user: `${interaction.user.tag} (${interaction.user.id})`,
            content,
          });
        } else {
          const { data, error } = await supabase
            .from('posts')
            .insert([
              {
                title: id.title,
                content: 'ここにテキストを入力してね',
                thumbnail_url: id.thumbnailUrl,
              },
            ])
            .select();

          if (error) {
            await sendErrorLog('Supabaseへの投稿保存失敗', error, {
              user: `${interaction.user.tag} (${interaction.user.id})`,
              title: id.title,
            });
          }
        }
      }
    } catch (error) {
      await sendErrorLog('動画掲載フロー処理失敗', error, {
        user: `${interaction.user.tag} (${interaction.user.id})`,
        customId: interaction.customId,
      });
      await interaction.message.delete().catch(() => {});
    }
  }
});

/**
 * 動画の情報を取得し、最短URLとタイトル、サムネイルURLを返す
 * @param {string} text
 * @returns {Promise<{url: string, title: string, thumbnailUrl: string}|null>}
 */
async function getAndSaveVideoInfo(text) {
  const combinedRegex =
    /(?:(?:https?:\/\/)?(?:www\.)?(?:youtube\.com\/(?:[^\/\n\s]+\/\S+\/|(?:v|e(?:mbed)?)\/|\S*?[?&]v=)|youtu\.be\/)([a-zA-Z0-9_-]{11}))|(?:(?:https?:\/\/)?(?:www\.)?nicovideo\.jp\/watch\/(sm\d+|so\d+|nm\d+))/;

  const match = text.match(combinedRegex);
  if (!match) return null;

  let sourceImageUrl = '';
  let videoUrl = '';
  let videoTitle = '無題の動画';
  const randomId = crypto.randomBytes(4).toString('hex');

  try {
    if (match[1]) {
      const videoId = match[1];
      videoUrl = `https://youtu.be/${videoId}`;
      sourceImageUrl = `https://img.youtube.com/vi/${videoId}/maxresdefault.jpg`;

      try {
        const oembed = await axios.get(
          `https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=${videoId}&format=json`
        );
        videoTitle = oembed.data.title;
      } catch (e) {
        /* fallback */
      }
    } else if (match[2]) {
      const videoId = match[2];
      videoUrl = `https://nico.ms/${videoId}`;

      try {
        const xmlResponse = await axios.get(`https://ext.nicovideo.jp/api/getthumbinfo/${videoId}`);
        const xmlData = xmlResponse.data;
        const titleMatch = xmlData.match(/<title>(.*?)<\/title>/);
        if (titleMatch) videoTitle = titleMatch[1];

        const thumbMatch = xmlData.match(/<thumbnail_url>(.*?)<\/thumbnail_url>/);
        sourceImageUrl = thumbMatch
          ? thumbMatch[1] + '.L'
          : `https://nicovideo.cdn.nimg.jp/thumbnails/${videoId}/${videoId}.L`;
      } catch (e) {
        sourceImageUrl = `https://nicovideo.cdn.nimg.jp/thumbnails/${videoId}/${videoId}.L`;
      }
    }

    let cloudinaryUrl = '';
    try {
      const result = await cloudinary.uploader.upload(sourceImageUrl, {
        public_id: `articles/${randomId}`,
        overwrite: false,
        transformation: [
          { width: 1200, height: 630, crop: 'fill', gravity: 'auto' },
          { fetch_format: 'auto', quality: 'auto' },
        ],
      });
      cloudinaryUrl = result.secure_url;
    } catch (error) {
      await sendErrorLog('Cloudinaryアップロード失敗（1回目）', error, {
        sourceImageUrl,
      });
      if (match[1]) {
        try {
          const retryUrl = `https://img.youtube.com/vi/${match[1]}/hqdefault.jpg`;
          const retryResult = await cloudinary.uploader.upload(retryUrl, { public_id: `articles/${randomId}` });
          cloudinaryUrl = retryResult.secure_url;
        } catch (retryError) {
          await sendErrorLog('Cloudinaryアップロード失敗（リトライ）', retryError, {
            videoId: match[1],
          });
        }
      }
    }

    return {
      url: videoUrl,
      title: videoTitle,
      thumbnailUrl: randomId,
    };
  } catch (error) {
    await sendErrorLog('動画情報取得処理失敗', error, { text });
    return null;
  }
}
